/** Maps Architex component names to HTML tags. */

export const TAG_MAP: Record<string, string> = {
  text:     'p',
  label:    'span',
  header:   'h2',
  h1:       'h1',
  h2:       'h2',
  h3:       'h3',
  h4:       'h4',
  h5:       'h5',
  h6:       'h6',
  button:   'button',
  btn:      'button',
  input:    'input',
  textarea: 'textarea',
  select:   'select',
  option:   'option',
  checkbox: 'input',
  toggle:   'input',
  image:    'img',
  img:      'img',
  box:      'div',
  row:      'div',
  col:      'div',
  card:     'div',
  scroll:   'div',
  divider:  'hr',
  spacer:   'div',
  badge:    'span',
  icon:     'span',
  link:     'a',
  modal:    'div',
  tabs:     'div',
  tab:      'div',
  range:    'input',
  slider:   'input',
  radio:    'input',
  progress: 'progress',
  form:     'form',
  // Table components
  table:    'table',
  thead:    'thead',
  tbody:    'tbody',
  tr:       'tr',
  td:       'td',
  th:       'th',
  // Media components
  video:    'video',
  audio:    'audio',
  source:   'source',
  canvas:   'canvas',
  // Toast / snackbar (rendered as div, special handling in component.ts)
  toast:    'div',
  snackbar: 'div',
  // Loading / async pattern components
  spinner:  'div',
  skeleton: 'div',
  // Advanced UI components
  accordion:    'div',
  carousel:     'div',
  bottomsheet:  'div',
  datepicker:   'input',
  search:       'div',
  avatar:       'div',
  chip:         'span',
  tag:          'span',
  stepper:      'div',
  wizard:       'div',
  infinitescroll: 'div',
  pullrefresh:  'div',
  // Round 3 components
  virtuallist:    'div',
  transitiongroup:'div',
  richtext:       'div',
  markdown:       'div',
  colorpicker:    'input',
  rating:         'div',
  tooltip:        'div',
  popover:        'div',
  breadcrumb:     'nav',
  pagination:     'nav',
  dropdown:       'div',
  gallery:        'div',
  lightbox:       'div',
  // Round 4 components
  sortablelist:     'div',
  commandpalette:   'div',
  datatable:        'div',
  treeview:         'div',
  tree:             'div',
  calendar:         'div',
  timeline:         'div',
  chatbubble:       'div',
  bubble:           'div',
  codeeditor:       'div',
  codeblock:        'div',
  signaturepad:     'div',
  signature:        'div',
  confetti:         'div',
  typewriter:       'span',
  countup:          'span',
  counter:          'span',
  otpinput:         'div',
  otp:              'div',
  fileupload:       'div',
  dropzone:         'div',
  sparkline:        'div',
  swipecard:        'div',
  circularprogress: 'div',
  circleprogress:   'div',
  audioplayer:      'div',
  videoplayer:      'div',
  qrcode:           'div',
  phoneinput:       'div',
  cropper:          'div',
  diffviewer:       'div',
  diff:             'div',
  kanban:           'div',
  meter:            'div',
  gauge:            'div',
  // Round 5 batch 1
  chart:        'canvas',
  heatmap:      'div',
  orgchart:     'div',
  funnel:       'div',
  splitpane:    'div',
  drawer:       'div',
  sidebar:      'div',
  bottomnav:    'nav',
  fab:          'div',
  speeddial:    'div',
  appbar:       'div',
  toolbar:      'div',
  terminal:     'div',
  // Round 5 batch 2
  autocomplete:     'div',
  taginput:         'div',
  wysiwyg:          'div',
  rangedual:        'div',
  dualrange:        'div',
  creditcard:       'div',
  emojipicker:      'div',
  mention:          'div',
  reactions:        'div',
  presence:         'span',
  thread:           'div',
};
